### ISSUE TITLE
怎样做到首页显示文章部分内容？

### ISSUE THREAD

**Issue by szu-bee** [BoizZ/hexo-theme-laughing#31]
想做到这样：
![image](https://user-images.githubusercontent.com/22913329/28834690-93281140-7715-11e7-9ac6-97d9d35184fd.png)

而我的显示只有标题：
![image](https://user-images.githubusercontent.com/22913329/28834748-c4a33ba0-7715-11e7-865d-e293a1df7d50.png)

**Comment by boizz** [comment]
在 md 中加个 `<!--more-->` 标签，标签上面的内容就会变成 description
